version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py createsu &&
      python manage.py loaddata testdata/fixtures/expenses_sample.json &&
      python manage.py loaddata testdata/fixtures/messeevent_sample.json &&
      python manage.py loaddata testdata/fixtures/pricecurrency_sample.json &&
      python manage.py loaddata testdata/fixtures/storagelocation_sample.json &&
      python manage.py loaddata testdata/fixtures/ingredient_sample.json &&
      python manage.py loaddata testdata/fixtures/portionunit_sample.json &&
      python manage.py loaddata testdata/fixtures/storageitem_sample.json &&
      python manage.py loaddata testdata/fixtures/userdata.json &&
      python manage.py loaddata testdata/fixtures/speise_sample.json &&
      python manage.py loaddata testdata/fixtures/recipe_sample.json &&
      python manage.py loaddata testdata/fixtures/recipeingredient_sample.json &&
      python manage.py loaddata testdata/fixtures/orderevent_sample.json &&
      python manage.py loaddata testdata/fixtures/order_final_sample.json &&
      python manage.py loaddata testdata/fixtures/orderitem2_sample.json &&
      python manage.py loaddata testdata/fixtures/ingredientusage_sample.json &&
      python3 manage.py runserver 0.0.0.0:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/frontend:/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_data:

