# Use a base image with Python
FROM python:3.12-slim

# Set environment variables for Python
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Install Gunicorn for running the application
RUN pip install gunicorn

# Copy the Django project files into the container
COPY . /app/

# Set environment variable for settings file in production
ENV DJANGO_SETTINGS_MODULE=backend.settings_prod

# Run migrations, collect static files, and create a superuser (optional)
RUN ls -la
RUN python backend/manage.py migrate
RUN python backend/manage.py collectstatic --noinput

# Expose the port your app will run on
EXPOSE 8000

# Start the application (replace with production-ready server like gunicorn)
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]

