# Generated by Django 5.1.2 on 2025-01-14 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speiseingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='speiselager',
            name='zutaten',
        ),
        migrations.RemoveField(
            model_name='speiseingredient',
            name='speise',
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('speise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='testdata.speise')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='testdata.recipe')),
            ],
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.recipeingredient'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='SpeiseIngredient',
        ),
        migrations.DeleteModel(
            name='SpeiseLager',
        ),
    ]
