# Generated by Django 5.1.2 on 2024-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speisen',
            old_name='ingredients',
            new_name='zutaten',
        ),
        migrations.RemoveField(
            model_name='speisen',
            name='instructions',
        ),
        migrations.AddField(
            model_name='speisen',
            name='menge',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speisen',
            name='preis',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speisen',
            name='r_preis',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speisen',
            name='rabatt',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
