# Generated by Django 5.1.2 on 2025-01-17 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0003_ingredient_remove_recipe_erstellt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='speise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.speise'),
        ),
    ]
