# Generated by Django 5.1.2 on 2024-11-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speise',
            name='menge',
        ),
        migrations.RemoveField(
            model_name='speise',
            name='r_preis',
        ),
        migrations.RemoveField(
            model_name='speise',
            name='rabatt',
        ),
    ]
