# Generated by Django 5.1.2 on 2025-01-21 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0004_alter_recipe_speise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Details about the product or its purpose.')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('FOOD', 'Essen & Getränke'), ('DECOR', 'Dekorationen'), ('COSTUME', 'Kostüme'), ('PROMO', 'Werbung & Promotion'), ('SUPPLY', 'Materialien'), ('EQUIP', 'Ausrüstung'), ('TRAVEL', 'Reisekosten'), ('FEES', 'Gebühren & Lizenzen'), ('MISC', 'Sonstiges')], help_text='Category of the expense.', max_length=10)),
                ('type', models.CharField(choices=[('I', 'Einkommen'), ('E', 'Ausgabe')], max_length=1)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity purchased.')),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('CC', 'Kreditkarte'), ('CA', 'Bargeld')])),
                ('handler', models.CharField(help_text='Person who did the payment')),
            ],
        ),
        migrations.CreateModel(
            name='PortionUnit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='name_ing',
        ),
        migrations.RenameField(
            model_name='speise',
            old_name='preis',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='storageitem',
            old_name='product',
            new_name='name_ingredient',
        ),
        migrations.RenameField(
            model_name='storageitem',
            old_name='quantity',
            new_name='total_stock',
        ),
        migrations.RenameField(
            model_name='storagelocation',
            old_name='name',
            new_name='name_loc',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='base_stock',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='portion_quantity',
        ),
        migrations.RemoveField(
            model_name='speise',
            name='erstellt',
        ),
        migrations.RemoveField(
            model_name='speise',
            name='zutaten',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='speise',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='speise',
            name='ordered_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='valid_until',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='speise',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testdata.portionunit'),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.portionunit'),
        ),
    ]
