# Generated by Django 5.1.2 on 2024-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0005_remove_speise_menge_remove_speise_r_preis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesseEvent',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
