# Generated by Django 5.1.2 on 2025-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0005_companyexpense_portionunit_pricecurrency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='base_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
    ]
