# Generated by Django 5.1.2 on 2024-11-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0006_messeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messeevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
