# Generated by Django 5.1.2 on 2025-01-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0006_ingredient_base_stock_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='speise',
            name='price_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testdata.pricecurrency'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testdata.portionunit'),
        ),
    ]
