# Generated by Django 5.1.2 on 2024-12-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0007_alter_messeevent_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('table', models.IntegerField()),
                ('waiter', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('events', models.ManyToManyField(to='testdata.orderevent')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem2',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('bom', models.JSONField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('events', models.ManyToManyField(related_name='order_item_events', to='testdata.orderevent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='testdata.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.FloatField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.order')),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.paymentoption')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.category')),
                ('attributes', models.ManyToManyField(to='testdata.productattribute')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.station')),
            ],
        ),
    ]
