# Generated by Django 5.1.2 on 2025-01-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0007_speise_price_unit_alter_ingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.ingredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdata.orderitem2')),
            ],
        ),
    ]
