# Generated by Django 5.1.2 on 2024-12-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0008_category_orderevent_paymentoption_productattribute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attributes',
            new_name='attribute',
        ),
    ]
