# Generated by Django 5.1.2 on 2025-01-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0008_ingredientusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity_per_portion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='total_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
