# Generated by Django 5.1.2 on 2025-01-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0009_alter_ingredient_base_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Zutat', 'verbose_name_plural': 'Zutaten'},
        ),
        migrations.AlterModelOptions(
            name='messeevent',
            options={'verbose_name': 'Messe / Event', 'verbose_name_plural': 'Messen / Events'},
        ),
        migrations.AlterModelOptions(
            name='portionunit',
            options={'verbose_name': 'Portionseinheit', 'verbose_name_plural': 'Portionseinheiten'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Rezept', 'verbose_name_plural': 'Rezepte'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Rezept Zutat', 'verbose_name_plural': 'Rezept Zutaten'},
        ),
        migrations.AlterModelOptions(
            name='speise',
            options={'verbose_name': 'Speise', 'verbose_name_plural': 'Speisen'},
        ),
    ]
