name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build and push React frontend Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/react-frontend:${{ github.sha }} -f frontend/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/react-frontend:${{ github.sha }}

    - name: Build and push Django backend Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/django-backend:${{ github.sha }} -f backend/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/django-backend:${{ github.sha }}

    - name: Build and push PostgreSQL image (optional)
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/postgresql:${{ github.sha }} -f db/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/postgresql:${{ github.sha }}

