name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Debug Working Directory
      run: pwd
    
    - name: Debug PYTHONPATH
      run: python -c "import sys; print(sys.path)"

    - name: Debug File Structure
      run: ls -R

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build and push React frontend Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/react-frontend:latest ./frontend
        docker push ghcr.io/${{ github.repository }}/react-frontend:latest

    - name: Build and push Django backend Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/django-backend:latest ./backend
        docker push ghcr.io/${{ github.repository }}/django-backend:latest

