name: Publish docker-compose
on:
  push:
      branches:
        - main


jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    - name: publish
      uses: soltys/publish-docker-compose@v1.0.0
      with:
        version: 'latest'
        docker_compose: './backend/docker-compose.build.yml'
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
