name: Django Backend and PostgreSQL Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-timeout=5s
          --health-interval=10s
          --health-retries=3

    steps:
      - name: Debug Working Directory
        run: pwd

      - name: Debug PYTHONPATH
        run: python -c "import sys; print(sys.path)"
      
      - name: Debug File Structure
        run: ls -R
      
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Step 4: Set environment variables for Django to use PostgreSQL
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/testdb" >> $GITHUB_ENV
          echo "DJANGO_SETTINGS_MODULE=backend.backend.settings_test" >> $GITHUB_ENV
        echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/business-intelligence/business-intelligence/backend/backend" >> $GITHUB_ENV

      - name: Test database connection
        run: |
          python -c "import psycopg2; psycopg2.connect('postgres://postgres:postgres@localhost:5432/testdb')"

      # Step 5: Run migrations
      - name: Run migrations
        run: |
          python backend/manage.py makemigrations --verbosity 3
          python backend/manage.py migrate

      # Step 6: Run tests
      - name: Run tests
        run: |
          python backend/manage.py test


